#!/bin/bash
# simple help script to change the IP of a cloned VM. The base image has the IP 192.168.124.99

if [ -z $1 ]
     then
       echo "change_ip <IP>"
       exit 0
fi
sed -i "s/192.168.124.99/$1/g" /etc/sysconfig/network/ifcfg-eth0
sed -i "s/192.168.124.99/$1/g" /etc/hosts
reboot

