#!/bin/bash
set +x
source ~/.clim
OPTINT=1
clear=""
verbose=0
notify=0

while getopts "ch?n" opt; do
   case "$opt" in
   h|\?)
     cat <<EOF
HELP:
  -c run config-processor with option "-e remove_deleted_servers=True -e free_unused_addresses=True"
  -n notify via pushover

COMMANDS
  prepare "MESSAGE": commits the config changes, run the config-processor and run the ready-deployment if the config is valid
  site             : deploys the config to the nodes via the site.yml playbook
  status	   : checks the status of the services
  stop		   : shutdown the openstack services
  start		   : start the openstack services
EOF
     exit 0
   ;;
   v)
     verbose=1
   ;;
   c) 
     clear="-e ..."
   ;;
   n)
     notify=1
   ;;
  esac
done

shift $(($OPTIND - 1))

[ "$1" = "--" ] && shift



case "$1" in
	prepare)
	  cd /var/lib/ardana//openstack/ardana/ansible
          if [ -z "$2" ]
	     then 
               echo "git commit message is missing: clim prepare \"MESSAGE\" "
               exit 3
          fi
          git add -A
	  git commit -m "$2"
          ansible-playbook -i hosts/localhost config-processor-run.yml 
          if [ $? -ne 0 ]
                then
                 echo ### ERROR: config-processor is not happy
                 exit 2
          fi
          echo ###########################################################################################################
          echo ###########################################################################################################
          echo ###########################################################################################################

          ansible-playbook -i hosts/localhost ready-deployment.yml
	  ;;


        site)
	  cd ~/scratch/ansible/next/ardana/ansible
          ansible-playbook -i hosts/verb_hosts site.yml
	  ;;

        start)
          cd ~/scratch/ansible/next/ardana/ansible
          ansible-playbook -i hosts/verb_hosts ardana-start.yml
          ;;

        stop)
          cd ~/scratch/ansible/next/ardana/ansible
          ansible-playbook -i hosts/verb_hosts ardana-stop.yml
          ;;

        status)
          cd ~/scratch/ansible/next/ardana/ansible
          ansible-playbook -i hosts/verb_hosts ardana-status.yml
          ;;

        test)
          echo Hallo
          echo $clear
          ;;

   	*)
          echo $"Usage: $0 cd_myconfig " 
	  exit 1
esac
if [ $notify -eq 1 ]
	then
         curl -s \
  --form-string "token=$push_token" \
  --form-string "user=$push_user" \
  --form-string "message=$push_msg" \
  --form-string "device=$push_device" \
  --form-string "title=$push_title" \
   $push_URL >/dev/null
fi



